services:
  backend:
    build: ./backend
    container_name: ymzxs_backend
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - DATABASE_URL=mysql+pymysql://root:password@mysql/ymzxs
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    restart: on-failure
    networks:
      - ymzxs-network

  frontend:
    build: ./frontend
    container_name: ymzxs_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ymzxs-network

  mysql:
    image: mysql:8.0
    container_name: ymzxs_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ymzxs
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ymzxs-network

  redis:
    image: redis:alpine
    container_name: ymzxs_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - ymzxs-network

networks:
  ymzxs-network:
    driver: bridge

volumes:
  mysql-data:
  redis-data: 