"""Add status and zones_json to StudyRoom model

Revision ID: 7be54a21dead
Revises: f3e54438127f
Create Date: 2025-04-05 12:46:54.464709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be54a21dead'
down_revision = 'f3e54438127f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'MAINTENANCE', name='roomstatus'), nullable=False))
        batch_op.add_column(sa.Column('zones_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_rooms', schema=None) as batch_op:
        batch_op.drop_column('zones_json')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
